"""email_account_viewers many-to-many, drop assigned_user_id

Revision ID: 594759debb7e
Revises: 5eae4c6f5824
Create Date: 2026-05-03 19:24:50.111132+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '594759debb7e'
down_revision: str | Sequence[str] | None = '5eae4c6f5824'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('email_account_viewers',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'user_id')
    )
    # SQLite: batch mode + naming_convention kell az unnamed FK drop-hoz
    naming = {"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}
    with op.batch_alter_table('email_accounts', schema=None, naming_convention=naming) as batch_op:
        batch_op.drop_constraint(
            "fk_email_accounts_assigned_user_id_users", type_='foreignkey'
        )
        batch_op.drop_column('assigned_user_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')

    op.drop_table('email_account_viewers')
    # ### end Alembic commands ###
