"""jobs: job_type field

Revision ID: 5443b628378f
Revises: 0d343b85680b
Create Date: 2026-05-03 10:48:05.759036+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '5443b628378f'
down_revision: str | Sequence[str] | None = '0d343b85680b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. job_type először nullable, hogy meglévő rekordok ne dőljenek el.
    with op.batch_alter_table("jobs_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_type", sa.String(length=30), nullable=True))

    # 2. Backfill: minden meglévő Job 'other' kategóriát kap (best-guess);
    #    a user a detail-en átállíthatja a megfelelőre.
    op.execute("UPDATE jobs_jobs SET job_type = 'other' WHERE job_type IS NULL")

    # 3. NOT NULL és index utólag.
    with op.batch_alter_table("jobs_jobs", schema=None) as batch_op:
        batch_op.alter_column("job_type", existing_type=sa.String(length=30), nullable=False)
        batch_op.create_index(batch_op.f("ix_jobs_jobs_job_type"), ["job_type"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_job_type'))
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
