"""customer: address fields

Revision ID: 0d343b85680b
Revises: c809e3b65593
Create Date: 2026-05-03 10:25:58.729146+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '0d343b85680b'
down_revision: str | Sequence[str] | None = 'c809e3b65593'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. `country` először nullable-ként, hogy meglévő rekordok ne törjenek el.
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("country", sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column("postal_code", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("city", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("address_line1", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("address_line2", sa.String(length=200), nullable=True))

    # 2. Backfill: minden meglévő ügyfél `Magyarország`-ot kap default-nak.
    op.execute("UPDATE customers SET country = 'Magyarország' WHERE country IS NULL")

    # 3. Most már NOT NULL-ra léptetjük.
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.alter_column("country", existing_type=sa.String(length=80), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')
        batch_op.drop_column('city')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
