"""customer: legal_type + tax_number

Revision ID: c809e3b65593
Revises: 755cfe9ddbc3
Create Date: 2026-05-03 10:15:55.150295+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = 'c809e3b65593'
down_revision: str | Sequence[str] | None = '755cfe9ddbc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. Új oszlopok hozzáadása. A `legal_type` először nullable-ként,
    #    hogy a meglévő rekordok ne törjenek el; a backfill után állítjuk
    #    NOT NULL-ra.
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("legal_type", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("tax_number", sa.String(length=20), nullable=True))

    # 2. Backfill: a meglévő `customer_type` alapján sejtjük a legal_type-ot.
    #    - reseller → company (jellemzően cégek viszonteladók)
    #    - retail   → individual (magánszemély vásárló)
    #    A user később admin UI-on átírhatja, ahol nem stimmel.
    op.execute(
        "UPDATE customers SET legal_type = 'company' "
        "WHERE legal_type IS NULL AND customer_type = 'reseller'"
    )
    op.execute(
        "UPDATE customers SET legal_type = 'individual' "
        "WHERE legal_type IS NULL"
    )

    # 3. Most már NOT NULL-ra léptethetjük.
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.alter_column("legal_type", existing_type=sa.String(length=20), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('tax_number')
        batch_op.drop_column('legal_type')

    # ### end Alembic commands ###
