"""email: supplier category + classification pipeline fields

Revision ID: e55368308b3a
Revises: b1b9dcb79de6
Create Date: 2026-05-03 18:03:52.719856+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = 'e55368308b3a'
down_revision: str | Sequence[str] | None = 'b1b9dcb79de6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_reply_to', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('thread_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('classified_by', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('imap_uid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('imap_deleted', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_incoming_emails_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_emails_thread_id'), ['thread_id'], unique=False)
        batch_op.drop_column('gemini_category')
        batch_op.drop_column('gemini_confidence')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_confidence', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gemini_category', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_index(batch_op.f('ix_incoming_emails_thread_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_emails_category'))
        batch_op.drop_column('imap_deleted')
        batch_op.drop_column('imap_uid')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('confidence')
        batch_op.drop_column('classified_by')
        batch_op.drop_column('category')
        batch_op.drop_column('thread_id')
        batch_op.drop_column('in_reply_to')

    # ### end Alembic commands ###
