"""email_accounts + incoming_emails + email_attachments

Revision ID: b1b9dcb79de6
Revises: f317dec1246b
Create Date: 2026-05-03 17:17:36.034245+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = 'b1b9dcb79de6'
down_revision: str | Sequence[str] | None = 'f317dec1246b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('email_address', sa.String(length=200), nullable=False),
    sa.Column('imap_host', sa.String(length=200), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_user', sa.String(length=200), nullable=False),
    sa.Column('imap_password_encrypted', sa.Text(), nullable=False),
    sa.Column('imap_use_ssl', sa.Boolean(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(), nullable=True),
    sa.Column('last_poll_uid', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('incoming_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('from_address', sa.String(length=300), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('to_address', sa.String(length=300), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('gemini_category', sa.String(length=30), nullable=True),
    sa.Column('gemini_confidence', sa.Float(), nullable=True),
    sa.Column('gemini_summary', sa.Text(), nullable=True),
    sa.Column('manual_category', sa.String(length=30), nullable=True),
    sa.Column('manual_category_by_id', sa.Integer(), nullable=True),
    sa.Column('matched_customer_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('converted_to_job_id', sa.Integer(), nullable=True),
    sa.Column('purged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['converted_to_job_id'], ['jobs_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manual_category_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incoming_emails_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_emails_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_emails_received_at'), ['received_at'], unique=False)

    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['incoming_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_attachments_email_id'), ['email_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_attachments_email_id'))

    op.drop_table('email_attachments')
    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incoming_emails_received_at'))
        batch_op.drop_index(batch_op.f('ix_incoming_emails_message_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_emails_account_id'))

    op.drop_table('incoming_emails')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
