"""jobs module: jobs, tasks, attachments

Revision ID: 755cfe9ddbc3
Revises: a40498bddf3a
Create Date: 2026-05-03 09:54:22.563698+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '755cfe9ddbc3'
down_revision: str | Sequence[str] | None = 'a40498bddf3a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=8), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('intake_user_id', sa.Integer(), nullable=False),
    sa.Column('intake_channel', sa.String(length=20), nullable=False),
    sa.Column('source_email_id', sa.Integer(), nullable=True),
    sa.Column('assigned_designer_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('price_huf', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_designer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['intake_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_jobs_assigned_designer_id'), ['assigned_designer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_intake_user_id'), ['intake_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_jobs_status'), ['status'], unique=False)

    op.create_table('jobs_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_attachments_job_id'), ['job_id'], unique=False)

    op.create_table('jobs_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_tasks_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tasks_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tasks_task_type'), ['task_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_tasks_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_tasks_assigned_to_user_id'))

    op.drop_table('jobs_tasks')
    with op.batch_alter_table('jobs_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_attachments_job_id'))

    op.drop_table('jobs_attachments')
    with op.batch_alter_table('jobs_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_public_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_intake_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_deadline'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_customer_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_assigned_designer_id'))

    op.drop_table('jobs_jobs')
    # ### end Alembic commands ###
