"""jobs: soft-delete + system_settings

Revision ID: f317dec1246b
Revises: 248ea0574be0
Create Date: 2026-05-03 11:17:24.083464+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = 'f317dec1246b'
down_revision: str | Sequence[str] | None = '248ea0574be0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table("jobs_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("deleted_by_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("delete_reason", sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f("ix_jobs_jobs_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_foreign_key(
            "fk_jobs_jobs_deleted_by_id_users",
            "users",
            ["deleted_by_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # Default system_settings rekordok beszúrása. Idempotens, mert
    # most került létre a tábla — biztos üres.
    op.execute(
        "INSERT INTO system_settings (key, value, description, updated_at) VALUES ("
        "'jobs.recycle_retention_days', "
        "'90', "
        "'Soft-deletált munkák tárolási ideje napokban. Ennél régebbieket "
        "a worker permanensen purge-elheti (Fázis 4-től).', "
        "CURRENT_TIMESTAMP"
        ")"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_jobs_deleted_at'))
        batch_op.drop_column('delete_reason')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    op.drop_table('system_settings')
    # ### end Alembic commands ###
