"""add avatar_initials and avatar_color to users

Revision ID: 5eae4c6f5824
Revises: e55368308b3a
Create Date: 2026-05-03 18:19:01.231061+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '5eae4c6f5824'
down_revision: str | Sequence[str] | None = 'e55368308b3a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_initials', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('avatar_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_color')
        batch_op.drop_column('avatar_initials')

    # ### end Alembic commands ###
