"""jobs: events table

Revision ID: 248ea0574be0
Revises: 5443b628378f
Create Date: 2026-05-03 11:06:30.183054+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '248ea0574be0'
down_revision: str | Sequence[str] | None = '5443b628378f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_events_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_events_created_at'))

    op.drop_table('jobs_events')
    # ### end Alembic commands ###
