"""rendelo module: categories, items, requests, request_lines, events

Revision ID: a40498bddf3a
Revises: 8da7472ca29c
Create Date: 2026-05-03 08:18:09.854031+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = 'a40498bddf3a'
down_revision: str | Sequence[str] | None = '8da7472ca29c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rendelo_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rendelo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('sizes', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('default_unit', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['rendelo_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category_id', name='uq_rendelo_item_name_category')
    )
    with op.batch_alter_table('rendelo_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rendelo_items_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_rendelo_items_category_id'), ['category_id'], unique=False)

    op.create_table('rendelo_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('ordered_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('order_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['rendelo_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rendelo_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rendelo_requests_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rendelo_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rendelo_requests_ordered_by_id'), ['ordered_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rendelo_requests_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rendelo_requests_status'), ['status'], unique=False)

    op.create_table('rendelo_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['rendelo_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rendelo_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rendelo_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rendelo_events_request_id'), ['request_id'], unique=False)

    op.create_table('rendelo_request_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('qty_arrived', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['rendelo_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['rendelo_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rendelo_request_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rendelo_request_lines_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rendelo_request_lines_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rendelo_request_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rendelo_request_lines_request_id'))
        batch_op.drop_index(batch_op.f('ix_rendelo_request_lines_item_id'))

    op.drop_table('rendelo_request_lines')
    with op.batch_alter_table('rendelo_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rendelo_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_rendelo_events_created_at'))

    op.drop_table('rendelo_events')
    with op.batch_alter_table('rendelo_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rendelo_requests_status'))
        batch_op.drop_index(batch_op.f('ix_rendelo_requests_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_rendelo_requests_ordered_by_id'))
        batch_op.drop_index(batch_op.f('ix_rendelo_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_rendelo_requests_category_id'))

    op.drop_table('rendelo_requests')
    with op.batch_alter_table('rendelo_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rendelo_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_rendelo_items_brand'))

    op.drop_table('rendelo_items')
    op.drop_table('rendelo_categories')
    # ### end Alembic commands ###
